In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import zipfile
import os

zip_path = "/content/got_of_thrones.zip"  # Change this to your actual file name
data = "/content/data"  # Change if needed

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(data)

print("Extraction complete.")


Extraction complete.


In [ ]:
print(os.listdir(data))

['004ssb.txt', '001ssb.txt', '003ssb.txt', '005ssb.txt', '002ssb.txt']


In [ ]:
!pip install gensim

In [ ]:
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
import gensim
!pip install nltk
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
import os
from nltk import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from gensim.utils import simple_preprocess

# Download stopwords if not already downloaded
import nltk
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))  # Load stopwords

story = []
for filename in os.listdir('data'):
    with open(os.path.join('data', filename), 'r', encoding='utf-8', errors='ignore') as f:
        corpus = f.read()
        raw_sent = sent_tokenize(corpus)
        for sent in raw_sent:
            words = simple_preprocess(sent)
            filtered_words = [word for word in words if word not in stop_words]  # Remove stopwords
            story.append(filtered_words)


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
story[:10]

[['version',
  'history',
  'reedited',
  'maelstrom',
  'feast',
  'crows',
  'book',
  'four',
  'song',
  'ice',
  'fire',
  'george'],
 ['martin', 'prologue', 'dragons', 'said', 'mollander'],
 ['snatched', 'withered', 'apple', 'ground', 'tossed', 'hand', 'hand'],
 ['throw', 'apple', 'urged', 'alleras', 'sphinx'],
 ['slipped', 'arrow', 'quiver', 'nocked', 'bowstring'],
 ['like', 'see', 'dragon'],
 ['roone',
  'youngest',
  'chunky',
  'boy',
  'still',
  'two',
  'years',
  'shy',
  'manhood'],
 ['like', 'much'],
 ['like', 'sleep', 'roseys', 'arms', 'around', 'pate', 'thought'],
 ['shifted', 'restlessly', 'bench']]

In [ ]:
len(story)

158874

In [ ]:
story

[['version',
  'history',
  'reedited',
  'maelstrom',
  'feast',
  'crows',
  'book',
  'four',
  'song',
  'ice',
  'fire',
  'george'],
 ['martin', 'prologue', 'dragons', 'said', 'mollander'],
 ['snatched', 'withered', 'apple', 'ground', 'tossed', 'hand', 'hand'],
 ['throw', 'apple', 'urged', 'alleras', 'sphinx'],
 ['slipped', 'arrow', 'quiver', 'nocked', 'bowstring'],
 ['like', 'see', 'dragon'],
 ['roone',
  'youngest',
  'chunky',
  'boy',
  'still',
  'two',
  'years',
  'shy',
  'manhood'],
 ['like', 'much'],
 ['like', 'sleep', 'roseys', 'arms', 'around', 'pate', 'thought'],
 ['shifted', 'restlessly', 'bench'],
 ['morrow', 'girl', 'could', 'well'],
 ['take',
  'far',
  'oldtown',
  'across',
  'narrow',
  'sea',
  'one',
  'free',
  'cities'],
 ['maesters', 'one', 'accuse'],
 ['could',
  'hear',
  'emmas',
  'laughter',
  'coming',
  'shuttered',
  'window',
  'overhead',
  'mingled',
  'deeper',
  'voice',
  'man',
  'entertaining'],
 ['oldest',
  'serving',
  'wenches',
  'qui

In [ ]:
model = gensim.models.Word2Vec(
    window=10,
  min_count=2,
)

In [ ]:
model.build_vocab(story)

In [ ]:
model.train(story, total_examples=model.corpus_count, epochs=model.epochs)

(4416747, 4596315)

In [ ]:
model.wv.most_similar('daenerys')

[('stormborn', 0.9158260822296143),
 ('unburnt', 0.8800726532936096),
 ('targaryen', 0.8402562737464905),
 ('elia', 0.8306996822357178),
 ('regent', 0.8271333575248718),
 ('conspired', 0.8154125213623047),
 ('myrcella', 0.7967694401741028),
 ('conceived', 0.7957411408424377),
 ('adultery', 0.7951608896255493),
 ('faime', 0.7934048771858215)]

In [ ]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [ ]:
model.wv.doesnt_match(['cersei','jaime','bronn','tyrion'])

'bronn'

In [ ]:
model.wv['stark']

array([-3.8755754e-01,  9.9608970e-01,  1.5041775e+00,  1.0416232e+00,
        1.2653106e-02, -8.0923086e-01,  3.5523975e-01,  1.1344143e+00,
       -8.0079758e-01, -4.8393261e-01,  1.0898156e+00, -9.6816790e-01,
        6.3182759e-01,  1.5099593e+00, -2.7630394e-02,  7.0357555e-01,
        2.2943008e-01, -5.7533497e-01, -2.1350291e-01, -1.3292512e+00,
       -1.1089007e+00,  1.7240537e+00,  1.2457294e+00, -2.7329395e+00,
        1.2043180e+00, -8.6172335e-02,  1.5791653e-03,  9.6404141e-01,
        8.2548875e-01,  5.9957385e-01,  1.4332653e+00,  3.7346208e-01,
        8.7336755e-01,  2.1548206e-01, -9.8159736e-01,  1.4014568e+00,
       -2.0983116e-01, -2.9228759e-01,  2.4611382e-01, -2.7626771e-01,
       -1.3495760e+00,  1.2328953e+00,  1.2363304e+00,  8.9183486e-01,
       -4.0044978e-02,  1.2294815e+00,  6.9263488e-02, -1.2085640e+00,
       -5.0170285e-01,  2.8613642e-02, -2.8705335e-01, -8.4421021e-01,
       -1.7911274e+00,  1.7970668e+00,  8.0946553e-01,  4.4917965e-01,
      

In [ ]:
model.wv.similarity('arya', 'sansa')

0.8245555

In [ ]:
model.wv.similarity('sansa', 'cersei')

0.7214018

In [ ]:
model.wv.get_normed_vectors()

array([[-0.0147706 ,  0.12178589,  0.01128559, ..., -0.08891286,
         0.04872612,  0.14865026],
       [-0.14057697,  0.1521467 ,  0.07884069, ..., -0.10771614,
        -0.08624371,  0.09743665],
       [-0.08545779,  0.02972839, -0.06395146, ..., -0.0649005 ,
         0.02604821, -0.10637145],
       ...,
       [-0.12210703,  0.09492389, -0.01757715, ..., -0.1014985 ,
         0.00549434,  0.02530717],
       [-0.11511666,  0.17541589, -0.04521046, ..., -0.14204969,
         0.02732992,  0.06892074],
       [-0.1100808 ,  0.11740487, -0.02631241, ..., -0.18293397,
        -0.03029071,  0.04929129]], dtype=float32)

In [ ]:
y = model.wv.index_to_key

In [ ]:
y[:100]

['said',
 'lord',
 'would',
 'one',
 'ser',
 'could',
 'man',
 'men',
 'back',
 'king',
 'well',
 'like',
 'jon',
 'old',
 'hand',
 'even',
 'never',
 'tyrion',
 'know',
 'see',
 'made',
 'father',
 'eyes',
 'black',
 'told',
 'thought',
 'lady',
 'time',
 'long',
 'might',
 'us',
 'come',
 'still',
 'face',
 'head',
 'red',
 'way',
 'page',
 'boy',
 'must',
 'good',
 'two',
 'little',
 'brother',
 'took',
 'came',
 'though',
 'say',
 'night',
 'three',
 'away',
 'queen',
 'dead',
 'son',
 'blood',
 'take',
 'go',
 'half',
 'make',
 'arya',
 'saw',
 'white',
 'day',
 'first',
 'jaime',
 'look',
 'want',
 'much',
 'enough',
 'tell',
 'sword',
 'great',
 'looked',
 'bran',
 'girl',
 'left',
 'knew',
 'asked',
 'gave',
 'called',
 'wall',
 'every',
 'heard',
 'maester',
 'yet',
 'went',
 'let',
 'sansa',
 'turned',
 'behind',
 'need',
 'dany',
 'around',
 'another',
 'beneath',
 'across',
 'snow',
 'keep',
 'gods',
 'found']

In [ ]:
import sklearn
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=3)

In [ ]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [ ]:
X[:5]

array([[ 0.44921082,  0.00648382,  0.24796352],
       [ 0.37294218,  0.60340995,  0.3966779 ],
       [ 0.47154912, -0.05748934, -0.3715724 ],
       [-0.06671329,  0.14899   , -0.06567676],
       [ 0.22624806,  0.535853  ,  0.5573103 ]], dtype=float32)

In [ ]:
X.shape

(17726, 3)

In [ ]:
import plotly.express as px
fig = px.scatter_3d(X[:100],x=0,y=1,z=2, color=y[:100])
fig.show()